config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'
  root 'home#index'

  post 'friendships/create'
  delete 'friendships/destroy'

  post 'loans/create'
  put 'loans/confirm'
  delete 'loans/destroy'

  get 'games/search', to: 'games#search', as: 'games_search'
  get 'games/result', to: 'games#result', as: 'games_result'

  get 'users/search', to: 'users#search', as: 'users_search'
  get 'users/result', to: 'users#result', as: 'users_result'

  resources :users, only: [:show] do
    resources :games, only: [:index, :show]
    post 'games/sync', to: 'games#sync', as: 'games_sync'
    post 'games/add', to: 'games#add', as: 'games_add'
    delete 'games/remove', to: 'games#remove', as:'games_remove'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :collections, foreign_key: :owner_id, dependent: :destroy
  has_many :games, through: :collections

  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", dependent: :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :loans, dependent: :destroy
  has_many :borrowers, through: :loans
  has_many :borrowings, class_name: "Loan", foreign_key: :borrower_id, dependent: :destroy
  has_many :borrowed_games, through: :loans, foreign_key: :game_id, source: :borrower
  has_many :loaned_games, through: :loans, foreign_key: :game_id, source: :user
  has_many :lenders, through: :loans, foreign_key: :user_id, source: :borrower

  validates :bgg_username, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
require 'pp'
require 'will_paginate/array'

class UsersController < ApplicationController

  def search

  end

  def result
    search_term = search_params[:search]

    @users = User.where("bgg_username ILIKE (?)", "%#{search_term}%").order(:bgg_username).reject { |user| user == current_user }
    @users = @users.paginate(:page => params[:page], :per_page => 20)
    respond_to do |format|
      format.html
      format.js
    end
  end


  def show
    @user = User.find(params[:id])
    @loans = @user.loans.where(status: "confirmed")
    pp @loans
    @requests = @user.loans.where(status: "requested")
    pp @requests
    @borrowings = @user.borrowings.where(status:"confirmed")
    pp @borrowings
    if @user.nil?
      flash.now[:alert] = "User Not Found"
      redirect_to users_path
    end
  end

  private

  def search_params
    params.permit(:search, :page)
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_follow.html.erb
<h3 class="text-center">Following</h3>
<ul class="list-group center-block">
  <% for friendship in profile.friendships %>
  <li class="list-group-item clearfix">
    <h3 class="friend-list">
      <%= link_to user_games_path(friendship.friend) do %>
      <strong><%= friendship.friend.bgg_username %></strong>
      <% end %>
      <span class="badge"><%= friendship.friend.games.count %> games</span>
      <span class="btn-group pull-right">
        <% if current_user.id == params[:id].to_i %>
        <%= button_to friendships_destroy_path, method: 'delete', class:'btn btn-danger btn-sm', params: {friend: friendship.friend.id, inverse: false} do %>
        <span class="glyphicon glyphicon-remove"></span><span class="hidden-sm hidden-xs"> Remove Friend</span>
        <% end %>
      </span>
    </h3>
    <% end %>
  </li>
  <% end %>
</ul>

<h3 class="text-center">Followers</h3>
<ul class="list-group center-block">
  <% for user in profile.inverse_friends %>
  <li class="list-group-item clearfix">
    <h3 class="friend-list">
      <%= link_to user_games_path(user) do %>
      <strong><%= user.bgg_username %></strong>
      <% end %>
      <span class="badge"><%= user.games.count %> games </span>
      <span class="btn-group pull-right">
        <% if current_user.id == params[:id].to_i %>
        <%= button_to friendships_destroy_path, method: 'delete', class:'btn btn-danger btn-sm', params: {friend: user.id, inverse: true} do %>
        <span class="glyphicon glyphicon-remove"></span><span class="hidden-sm hidden-xs"> Remove Friend</span>
        <% end %>
        <% end %>
      </span>
    </h3>
  </li>
  <% end %>
</ul>

app/views/users/_list.html.erb
<% if users.any? %>
  <% users.each do |user| %>
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="panel panel-default ">
        <div class="panel-heading user-panel-heading highlight">
          <h3 class="user-panel-title"><%= user.bgg_username %>
            <span class="glyphicon glyphicon-triangle-bottom pull-right" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-triangle-top pull-right hide-content" aria-hidden="true"></span>
          </h3>
        </div>
        <div class="panel-body user-panel-body hide-content">
          <div class="row">
            <div class="col-xs-12 col-sm-2 col-md-3 text-center user-panel-side">
              <%= image_tag(user.image, class: "user-panel-image img-responsive") %>
              <%= link_to user_games_path(user), class:"btn btn-info btn-responsive center-block btn-sm" do %>
                  <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
                  <span class="sr-only">Link to User Collection</span><%= user.bgg_username%>'s Collection
              <% end %>
              <%= link_to friendships_create_path(:friend_id => user), method: 'post', class:'btn btn-success btn-responsive center-block btn-sm' do %>
                <span class="glyphicon glyphicon-user"></span> Add Friend
              <% end %>
            </div>
            <div class="col-xs-12 col-sm-10 col-md-9">
              <%= link_to user_path(user), method: 'get' do %>
                <h4>User Info</h4>
              <% end %>
              <ul class="list-group">

                <li class="list-group-item user-list">
                  Games owned: <%= user.games.count %>
                </li>
                <li class="list-group-item user-list">Following: <%= user.friends.count%></li>
                <li class="list-group-item user-list">Followed: <%= user.inverse_friends.count %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row pagination-links">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 text-center well well-small bg-info">
      <p class="user-page-info">
        <%= page_entries_info users %>
      </p>
      <%= will_paginate users, :page_links => true %>

    </div>
  </div>
<% else %>
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <h3 class="text-center">No Results Available</h3>
  </div>
<% end %>

app/views/users/_rentals.html.erb
<h3 class="text-center">Loaned Games</h3>
<ul class="list-group center-block">
  <% if loans == [] %>
    <li class="list-group-item clearfix">
      <h4 class="loaned-games-list text-center">No Loaned Games</h4>
    </li>
  <% end %>
  <% loans.each do |loan| %>
    <li class="list-group-item clearfix">
      <h3 class="loaned-games-list">
        <strong><%= loan.game.name %></strong>
        <br>
        <span class="badge"><%= loan.borrower.bgg_username %></span>
        <span class="badge"><%= loan.updated_at.strftime("%m/%e/%y") %></span>
        <span class="btn-group pull-right">
          <% if current_user.id == params[:id].to_i %>
            <%= button_to loans_destroy_path, method: 'delete', class:'btn btn-danger btn-sm', params: {loan_id: loan.id} do %>
              <span class="glyphicon glyphicon-remove"></span><span class="hidden-sm hidden-xs"> Game Returned</span>
            <% end %>
          <% end %>
        </span>
      </h3>
    </li>
  <% end %>
</ul>
<h3 class="text-center">Pending Loan Requests</h3>
<ul class="list-group center-block">
  <% if requests == [] %>
    <li class="list-group-item clearfix">
      <h4 class="loaned-games-list text-center">No Pending Requests</h4>
    </li>
  <% end %>
  <% requests.each do |request| %>
    <li class="list-group-item clearfix">
      <h3 class="loaned-games-list">
        <strong><%= request.game.name %></strong>
        <br>
        <span class="badge"><%= request.borrower.bgg_username %></span>
        <span class="badge"><%= request.updated_at.strftime("%m/%e/%y") %></span>
        <div class="btn-group inline-block pull-right">
          <% if current_user.id == params[:id].to_i %>
          <div class="btn-group">
            <%= button_to loans_confirm_path, method: 'put', class:'btn btn-success btn-sm', params: {loan_id: request.id} do %>
              <span class="glyphicon glyphicon-ok"></span><span class="hidden-sm hidden-xs"> Approve?</span>
            <% end %>
          </div>
          <% end %>
          <% if current_user.id == params[:id].to_i || current_user == request.borrower %>
          <div class="btn-group">
            <%= button_to loans_destroy_path, method: 'delete', class:'btn btn-danger btn-sm', params: {owner_id: request.user.id, loan_id: request.id} do %>
              <span class="glyphicon glyphicon-remove"></span><span class="hidden-sm hidden-xs"> Remove Request</span>
            <% end %>
          </div>
          <% end %>
        </div>
      </h3>
    </li>
  <% end %>
</ul>
<h3 class="text-center"><%= profile.bgg_username%>'s Borrowed Games</h3>
<ul class="list-group center-block">
  <% if borrowings == [] %>
    <li class="list-group-item clearfix">
      <h4 class="loaned-games-list text-center">No Borrowed Games</h4>
    </li>
  <% end %>
  <% borrowings.each do |borrowed| %>
    <li class="list-group-item clearfix">
      <h3 class="loaned-games-list">
        <strong><%= borrowed.game.name %></strong>
        <br>
        <span class="badge"><%= borrowed.user.bgg_username %></span>
        <span class="badge"><%= borrowed.updated_at.strftime("%m/%e/%y") %></span>
      </h3>
    </li>
  <% end %>
</ul>

app/views/users/result.html.erb
<div class="row">
  <div id="results-list">
      <h2 class="text-center">Search Results</h2>
    <%= render partial: 'list', locals: {users: @users} %>
  </div>
</div>

app/views/users/result.js.erb
$("#results-list").html("<%= escape_javascript(render partial: 'list', locals: { users: @users } ) %>");

app/views/users/search.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="page-header">
      <h1 class="text-center">Search Fellow Boardgamers</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
  <%= form_tag users_result_path, remote: true, :method => 'get', class: 'input-group'  do %>
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search for...' %>
    <span class="input-group-btn">
      <%= button_tag type:'submit', class: "btn btn-primary", id:'search-button' do %>
      <span class="glyphicon glyphicon-search"></span> Search
      <% end %>
    </span>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="loading">
    <h3 class="text-center">Loading Results ...</h3>
  </div>
  <div id="results-list">
    <!-- render partial here -->
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-container">
  <div class="row">
    <div class="col-xs-12 col-sm-3">
      <%= image_tag(@user.image, class: "user-image img-responsive center-block img-thumbnail") %>
    </div>
    <div class="col-xs-12 col-sm-9">
      <h2 class="text-center"><%= @user.bgg_username%>'s <small>Profile Page</small></h2>
      <div class="user-links text-center">
        <% if current_user.id == params[:id].to_i %>
          <%= link_to edit_user_registration_path, class:'btn btn-primary' do%>
            <span class="glyphicon glyphicon-edit"></span> Edit Profile
          <% end %>
        <% else %>
          <%= link_to friendships_create_path(:friend_id => @user), :method => :post, class:'btn btn-success' do %>
            <span class="glyphicon glyphicon-user"></span> Add Friend
          <% end %>
        <% end %>
        <%= link_to user_games_path(@user), class:'btn btn-info' do %>
          <span class="glyphicon glyphicon-tower"></span> <%= @user.bgg_username%>'s Collection
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-0">
      <%= render partial: "follow", locals: {profile: @user} %>
    </div>
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-0">
      <%= render partial: "rentals", locals: {profile: @user, loans: @loans, borrowings: @borrowings, requests: @requests} %>
    </div>
  </div>
</div>