config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'
  root 'home#index'

  post 'friendships/create'
  delete 'friendships/destroy'

  post 'loans/create'
  put 'loans/confirm'
  delete 'loans/destroy'

  get 'games/search', to: 'games#search', as: 'games_search'
  get 'games/result', to: 'games#result', as: 'games_result'

  get 'users/search', to: 'users#search', as: 'users_search'
  get 'users/result', to: 'users#result', as: 'users_result'

  resources :users, only: [:show] do
    resources :games, only: [:index, :show]
    post 'games/sync', to: 'games#sync', as: 'games_sync'
    post 'games/add', to: 'games#add', as: 'games_add'
    delete 'games/remove', to: 'games#remove', as:'games_remove'
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :collections, dependent: :destroy
  has_many :owners, through: :collections
  has_many :loans

  validates :name, :description, presence: true
  validates :bgg_id, uniqueness: true
end

app/controllers/games_controller.rb
require 'pp'
require 'will_paginate/array'
class GamesController < ApplicationController
  before_action :find_user, except: [:search, :result]
  include CollectionUpdater
  include BggSearch
  def sync
    collection = CollectionUpdater.get_bgg_collection(@user)
    CollectionUpdater.sync_collection(@user, collection)
    redirect_to user_games_path(@user)
  end

  def add
    game_data = BggSearch.get_game_info(params[:game_id])
    @game = CollectionUpdater.add_to_collection(@user, game_data['item'][0])
    if @game.errors.empty?
      flash[:success] = "Game Added Successfully"
      redirect_to user_games_path(@user)
    else
      flash[:error] = "Unable to add Game"
      redirect_to games_search_path
    end
  end

  def search

  end

  def result
    search_term = search_params[:search]
    @games = BggSearch.search_bgg(search_term).paginate(:page => params[:page], :per_page => 30)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def remove
    if @user == current_user
      @game = @user.games.find(params[:game_id])
      if @game
        @user.games.delete(@game)
      end
      respond_to do |format|
        format.html
        format.js
      end
    else
      redirect_to user_games_path(current_user)
    end
  end

  def index
    @games = @user.games.order(:name).page(params[:page]).per_page(10)
  end

  def show
    @game = Game.find(params[:id])
    @details = BggSearch.get_game_details(@game.bgg_id)
    @parameters = [:recommended_minimum_age, :max_players, :min_players, :playing_time, :mechanics, :designers, :categories]
    @parameters.each do |parameter|
      pp parameter.to_s.gsub(/_/," ")
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def search_params
    params.permit(:search, :page)
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def current_user_page
    params[:user_id].to_i == current_user.id
  end
end

app/views/games/_list.html.erb
<% if games.any? %>
  <% games.each do |game| %>
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="panel panel-default ">
        <div class="panel-heading game-panel-heading highlight">
          <h3 class="game-panel-title"><%= game.name %>
            <span class="glyphicon glyphicon-triangle-bottom pull-right" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-triangle-top pull-right hide-content" aria-hidden="true"></span>
          </h3>
        </div>
        <div class="panel-body game-panel-body hide-content">
          <div class="row">
            <div class="col-xs-12 col-sm-2 col-md-3 text-center">
              <%= image_tag(game.image, class: "game-panel-image img-responsive") %>
              <%= link_to(game.bgg_link) do%>
                <div class="text-center">
                  <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
                  <span class="sr-only">Link to BGG Listing</span>
                  BGG Game Listing
                </div>
              <% end %>
              <%= button_to user_games_add_path(current_user), method: 'post', params: {game_id: game.bgg_id}, class:"btn btn-success btn-responsive center-block add-button btn-sm" do %>
                  <span class="glyphicon glyphicon-plus"></span> Add to Collection
              <% end %>
            </div>
            <div class="col-xs-12 col-sm-10 col-md-9">
              <h4>Game Description</h4>
              <p class="game-panel-text">
                <%= game.description.html_safe %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row pagination-links">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 text-center well well-small bg-info">
      <p class="game-page-info">
        <%= page_entries_info games %>
      </p>
      <%= will_paginate games, :page_links => true %>

    </div>
  </div>
<% else %>
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <h3 class="text-center">No Results Available</h3>
  </div>
<% end %>

app/views/games/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="page-header">
      <%= image_tag(@user.image, class: "profile-image img-fluid img-rounded center-block", alt: "User Image") %>
      <%= link_to user_path(@user) do %>
        <h1 class="text-center"><%= @user.bgg_username %>'s <small>Game Collection</small></h1>
      <% end %>
    </div>
  </div>
</div>

<!-- list out players games -->
<div class=row>
  <% @games.each do |game| %>
    <div class="col-xs-12 col-sm-10 col-sm-offset-1" id="game-<%= game.id.to_s %>">
      <div class="panel panel-default ">
        <div class="panel-heading game-panel-heading highlight">
          <h3 class="game-panel-title"><%= game.name %>
            <span class="glyphicon glyphicon-triangle-bottom pull-right" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-triangle-top pull-right hide-content" aria-hidden="true"></span>
          </h3>
        </div>
        <div class="panel-body game-panel-body hide-content">
          <div class="row">
            <div class="col-xs-12 col-sm-2 col-md-3">
              <%= image_tag(game.image, class: "game-panel-image img-responsive") %>
              <%= link_to(game.bgg_link) do%>
                <div class="text-center">
                  <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
                  <span class="sr-only">Link to BGG Listing</span>
                  BGG Game Listing
                </div>
              <% end %>
              <% if current_user_page %>
                <%= button_to user_games_remove_path(current_user), method: 'delete', params: {game_id: game.id}, class:"btn-responsive btn btn-danger remove-button center-block btn-sm", remote: true do %>
                    <span class="glyphicon glyphicon-remove"></span> Remvove from Collection
                <% end %>
              <% else %>
                <% if @user.friends.include?(current_user) %>
                  <%= button_to loans_create_path, method: 'post', params: {owner_id: @user.id, game_id: game.id}, class:"btn-responsive btn btn-primary request-button center-block btn-sm" do %>
                      <span class="glyphicon glyphicon-hand-right"></span> Borrow?
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <%= link_to user_game_path(@user, game) do %>
              <div class="col-xs-12 col-sm-10 col-md-9">
                <h4>Game Description</h4>
                <p class="game-panel-text">
                  <%= game.description.html_safe %>
                </p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<!-- pagination -->
<div class="row pagination-links">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 text-center well well-small bg-info">
    <p class="game-page-info">
      <%= page_entries_info @games %>
    </p>
    <%= will_paginate @games, :page_links => true %>

  </div>
</div>

<!-- add link to sync BGG account -->

<% if current_user_page %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <%= link_to 'Sync Account to Boardgame Geek', user_games_sync_path(current_user), class:'btn btn-primary center-block', method: 'post' %>
  </div>
</div>
<% end %>

app/views/games/remove.js.erb
$('#game-' + <%= @game.id %>).remove();

app/views/games/result.html.erb
<div class="row">
  <div id="results-list">
      <h2 class="text-center">Search Results</h2>
    <%= render partial: 'list', locals: {games: @games} %>
  </div>
</div>

app/views/games/result.js.erb
$("#results-list").html("<%= escape_javascript(render partial: 'list', locals: { games: @games } ) %>");

app/views/games/search.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="page-header">
      <h1 class="text-center">Search BGG for Games</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
  <%= form_tag games_result_path, remote: true, :method => 'get', class: 'input-group'  do %>
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search for...' %>
    <span class="input-group-btn">
      <%= button_tag type:'submit', class: "btn btn-primary", id:'search-button' do %>
      <span class="glyphicon glyphicon-search"></span> Search
      <% end %>
    </span>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="loading">
    <h3 class="text-center">Loading Results ...</h3>
  </div>
  <div id="results-list">
    <!-- render partial here -->
  </div>
</div>

app/views/games/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="text-center"><%= @game.name %>
      <br>
      <small>Published: <%= @details.year_published %></small>
    </h1>
  </div>

</div>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-0 col-md-4">
    <%= image_tag(@game.image, class: "game-panel-image img-responsive") %>
  </div>
  <div class="col-xs-10 col-xs-offset-1 col-sm-9 col-sm-offset-0 col-md-8">
    <h3>Game Description:</h3>
    <br>
    <p class="lead"><%= @game.description.html_safe %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h3 class="text-center">Game Details</h3>
    <table class="table">
      <% @parameters.each do |parameter| %>
        <tr>
          <td class="text-center">
            <%= parameter.to_s.gsub(/_/, " ") %>
          </td>
          <td class="text-center">
            <%= @details.method(parameter).call.kind_of?(Array) ? @details.method(parameter).call.join(' / ') : @details.method(parameter).call %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

</div>