config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'
  root 'home#index'

  post 'friendships/create'
  delete 'friendships/destroy'

  post 'loans/create'
  put 'loans/confirm'
  delete 'loans/destroy'

  get 'games/search', to: 'games#search', as: 'games_search'
  get 'games/result', to: 'games#result', as: 'games_result'

  get 'users/search', to: 'users#search', as: 'users_search'
  get 'users/result', to: 'users#result', as: 'users_result'

  resources :users, only: [:show] do
    resources :games, only: [:index, :show]
    post 'games/sync', to: 'games#sync', as: 'games_sync'
    post 'games/add', to: 'games#add', as: 'games_add'
    delete 'games/remove', to: 'games#remove', as:'games_remove'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boardgame Social</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to 'Boardgame Social', root_path, class: 'navbar-brand' %>
          </div>
          <div id="navbar">
            <ul class="nav navbar-nav pull-right">
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <%= current_user.bgg_username %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Search Users', users_search_path %></li>
                    <li><%= link_to 'Profile', user_path(current_user) %></li>
                    <li><%= link_to 'Search BGG', games_search_path %></li>
                    <li>
                      <%= link_to 'Collection', user_games_path(current_user)%>
                    </li>
                    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to 'Log In', new_user_session_path %></li>
                <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="wrapper">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <div class="container">
          <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>
        </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>